disabled_rules:
  - implicit_getter
  - nesting
  - redundant_string_enum_value
  - large_tuple
  - switch_case_alignment
  - colon
  - identifier_name
  - line_length
  - function_body_length
  - type_body_length
  - force_cast
  - for_where
  - file_length
excluded:
  - Pods
switch_case_alignment:
  indented_cases: true
