name: CI
on: push

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SwiftLint
        run: ./Pods/SwiftLint/swiftlint
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: xcodebuild -scheme Pods-EventsManager -workspace EventsManager.xcworkspace -quiet clean build
