name: CI
on: push

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Dependencies
        run: pod install
      - name: Run SwiftLint
        run: ./Pods/SwiftLint/swiftlint
      - name: Try to autocorrect
        run: ./Pods/SwiftLint/swiftlint autocorrect
      - name: Check SwiftLint style
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "You have some swiftlint problems that can be autocorrected."
            echo "Please run ./Pods/SwiftLint/swiftlint autocorrect before commit."
          else
            echo "Style is good!"
          fi
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Dependencies
        run: pod install
      - name: Build
        run: xcodebuild -scheme Pods-EventsManager -workspace EventsManager.xcworkspace -quiet clean build
